# Generated by Django 5.2.3 on 2025-07-18 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_attire_food_story'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attire',
        ),
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.DeleteModel(
            name='Story',
        ),
    ]
